apiVersion: v1
kind: Namespace
metadata:
  name: my-app-namespace  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-app-namespace
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: node-test2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URI
            value: "mongodb://mongo-service:27017"  
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: my-app-namespace
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017  
    targetPort: 27017  
  type: ClusterIP  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: my-app-namespace
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
