apiVersion: v1
kind: Namespace
metadata:
  name: my-app-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: my-app-namespace
type: Opaque
stringData:
  mongo-uri: "mongodb://10.244.0.255:27017/dispositivosDB"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-app-namespace
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: node-test2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: mongo-uri-volume
            mountPath: /etc/mongo-uri
            readOnly: true
      volumes:
        - name: mongo-uri-volume
          secret:
            secretName: my-app-secret
            items:
              - key: mongo-uri
                path: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: my-app-namespace
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: my-app-namespace
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
