version: '3'

services:
  reaction:
    build: .
    networks:
      - net
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      ROOT_URL: "http://localhost"
      MONGO_URL: "mongodb://mongo:27017/dispositivosDB1"
  mongo:
    image: mongo
    volumes:
      - $PWD/data:/data/db
    networks:
      - net

networks:
  net:
